"""The Black Ops zombies maps prepared from the installed game (all on E:).

zone: the map's own extracted fastfile; search: zones searched for its
assets, newest first; english: its localized zone (voice and sounds)."""
BO1_MAPS = {
    'five': dict(id='five',zone='bo1-five',asset='zombie_pentagon',data='gameplay/bo1-five',english='bo1-five-english',
        search=['bo1-five-patch','bo1-five','bo1-common','bo1-base','bo1-five-english','bo1-english','bo1-ui'],
        bodies=[{'name':'John F. Kennedy','body':'c_usa_pent_jfk_fb_zt'},
                {'name':'Robert McNamara','body':'c_usa_pent_mcnamara_fb_zt'},
                {'name':'Richard Nixon','body':'c_usa_pent_nixon_fb_zt'},
                {'name':'Fidel Castro','body':'c_cub_pent_castro_fb_zt'}]),
    'shangri-la': dict(id='shangri-la',zone='bo1-temple',asset='zombie_temple',data='gameplay/bo1-temple',english='bo1-temple-english',
        search=['bo1-temple-patch','bo1-temple','bo1-common','bo1-base','bo1-temple-english','bo1-english','bo1-ui'],
        bodies=[{'name':'Dempsey','body':'c_usa_dempsey_body'},
                {'name':'Nikolai','body':'c_rus_nikolai_body'},
                {'name':'Takeo','body':'c_jap_takeo_body'},
                {'name':'Richtofen','body':'c_ger_richtofen_body','head':'c_ger_richtofen_head','hat':'c_ger_richtofen_offcap'}]),
    'kino': dict(id='kino', zone='bo1-kino', asset='zombie_theater', data='gameplay/bo1-kino', english='bo1-english',
                 search=['bo1-kino', 'bo1-common', 'bo1-base', 'bo1-english', 'bo1-ui'],
                 bodies=[{'name': 'Dempsey', 'body': 'c_usa_dempsey_body'},
                         {'name': 'Nikolai', 'body': 'c_rus_nikolai_body'},
                         {'name': 'Takeo', 'body': 'c_jap_takeo_body'},
                         {'name': 'Richtofen', 'body': 'c_ger_richtofen_body', 'head': 'c_ger_richtofen_head', 'hat': 'c_ger_richtofen_offcap'}]),
    'ascension': dict(id='ascension', zone='bo1-cosmodrome', asset='zombie_cosmodrome', data='gameplay/bo1-cosmodrome', english='bo1-cosmodrome-english',
                      search=['bo1-cosmodrome-patch', 'bo1-cosmodrome', 'bo1-common', 'bo1-base', 'bo1-cosmodrome-english', 'bo1-english', 'bo1-ui'],
                      # character/c_*_dlc2.gsc: the crew's Ascension outfits.
                      bodies=[{'name': 'Dempsey', 'body': 'c_usa_dempsey_dlc2_body'},
                              {'name': 'Nikolai', 'body': 'c_rus_nikolai_dlc2_body'},
                              {'name': 'Takeo', 'body': 'c_jap_takeo_dlc2_body'},
                              {'name': 'Richtofen', 'body': 'c_ger_richtofen_dlc2_body'}]),
    'call-of-the-dead': dict(id='call-of-the-dead',zone='bo1-coast',asset='zombie_coast',data='gameplay/bo1-coast',english='bo1-coast-english',
        search=['bo1-coast-patch','bo1-coast','bo1-common','bo1-base','bo1-coast-english','bo1-english','bo1-ui'],
        bodies=[{'name':'Sarah Michelle Gellar','body':'c_zom_sarah_michelle_gellar_fb_player'},
                {'name':'Robert Englund','body':'c_zom_robert_englund_fb_player'},
                {'name':'Danny Trejo','body':'c_zom_danny_trejo_fb_player'},
                {'name':'Michael Rooker','body':'c_zom_michael_rooker_fb_player'}]),
    'moon': dict(id='moon',zone='bo1-moon',asset='zombie_moon',data='gameplay/bo1-moon',english='bo1-moon-english',
        search=['bo1-moon-patch','bo1-moon','bo1-common','bo1-base','bo1-moon-english','bo1-english','bo1-ui'],
        bodies=[{'name':'Dempsey','body':'c_usa_dempsey_dlc5_body','head':'c_usa_dempsey_dlc5_head'},
                {'name':'Nikolai','body':'c_rus_nikolai_dlc5_body','head':'c_rus_nikolai_dlc5_head'},
                {'name':'Takeo','body':'c_jap_takeo_dlc5_body','head':'c_jap_takeo_dlc5_head'},
                {'name':'Richtofen','body':'c_ger_richtofen_dlc5_body','head':'c_ger_richtofen_dlc5_head'}]),
}
