import assert from 'node:assert/strict';
import fs from 'node:fs';
import {SoloGame} from '../web/game.js';
import {CollisionWorld} from '../web/collision.js';
import {scorePopupState} from '../web/score-hud.js';
const read=p=>JSON.parse(fs.readFileSync(new URL('../local-data/'+p,import.meta.url)));
const manifest=read('gameplay/manifest.json'),collision=read('nacht/web-world/nazi_zombie_prototype.collision.json'),paths=read('nacht/web-world/nazi_zombie_prototype.paths.json');
const sounds=[],awards=[];
const game=new SoloGame(manifest,new CollisionWorld(collision,manifest.entities),paths,{sound:s=>sounds.push(s.alias),score:s=>awards.push(s.amount)});
game.start();game.round=1;game.roundDue=1e9;
const target={health:100,position:game.player.position.slice(),dead:false};
game.hitEnemy(target,10);assert.equal(awards.at(-1),10);
const popup=game.scorePopups.at(-1),start=scorePopupState(popup,game.time);
assert.equal(start.text,'+10');assert.equal(start.color,'#e6e600');assert.equal(start.alpha,1);
assert.equal(scorePopupState(popup,game.time+.25).alpha,1);
assert.equal(scorePopupState(popup,game.time+.375).alpha,.5);
assert.equal(scorePopupState(popup,game.time+.5),null);
assert(popup.moveX<=-20&&popup.moveX>=-59);assert(popup.moveY<=15&&popup.moveY>=-14);
game.powerup.double_points=30;game.hitEnemy(target,10);assert.equal(awards.at(-1),20);
game.hitEnemy(target,100,true);assert.equal(awards.at(-1),2*Math.ceil((manifest.variables.zombie_score_kill+manifest.variables.zombie_score_bonus_head)/10)*10);
delete game.powerup.double_points;
const barrier=game.windows[0];barrier.boards=4;const beforeRepair=game.player.points;game.rebuild(barrier);
assert.equal(barrier.boards,5);assert.equal(game.player.points,beforeRepair+10);assert.equal(awards.at(-1),10);assert.equal(sounds.at(-1),'repair_boards');
const soundCount=sounds.length;game.rebuild(barrier);assert.equal(sounds.length,soundCount,'A held repair cooldown must not spam sounds');
game.time=1;barrier.traverser={dead:false};game.rebuild(barrier);assert.equal(sounds.length,soundCount,'An occupied vault cannot rebuild or make a repair sound');
barrier.traverser=null;game.powerup.double_points=30;game.rebuild(barrier);assert.equal(awards.at(-1),20);delete game.powerup.double_points;
game.time=2;barrier.boards=5;game.barrierReward=50;const capped=game.player.points,awardCount=awards.length;game.rebuild(barrier);
assert.equal(game.player.points,capped);assert.equal(awards.length,awardCount,'A capped repair must not show an unearned award');assert.equal(sounds.at(-1),'repair_boards');
const interact=e=>{const p=e.origin.split(/\s+/).map(Number);game.player.position=[p[0],p[1],p[2]-35];game.use();};
const wall=game.interactions.find(e=>e.zombie_weapon_upgrade==='kar98k');game.player.points=5000;
interact(wall);assert.equal(game.weapon.name,'kar98k');assert.equal(awards.at(-1),-Number(wall.zombie_cost));assert(sounds.slice(-2).includes('cha_ching'),'A purchase plays cha_ching (then the weapon switch putaway)');
const deduction=scorePopupState(game.scorePopups.at(-1),game.time);assert.equal(deduction.text,String(-Number(wall.zombie_cost)));assert.equal(deduction.color,'#6c0100');
interact(wall);assert.equal(awards.at(-1),-Number(wall.script_ammo_clip||Number(wall.zombie_cost)*.5));assert.equal(sounds.at(-1),'cha_ching');
game.player.points=0;const rejectedAwards=awards.length;interact(wall);assert.equal(game.player.points,0);assert.equal(awards.length,rejectedAwards);assert.equal(sounds.at(-1),'no_cha_ching');
game.player.points=5000;const boxEntity=game.interactions.find(e=>e.targetname==='treasure_chest_use');interact(boxEntity);
assert.equal(awards.at(-1),-950);assert.equal(sounds.slice(-3).join(','),'cha_ching,lid_open,music_box');
const bought=awards.length,soundAfterBox=sounds.length;game.use();assert.equal(awards.length,bought);assert.equal(sounds.length,soundAfterBox);
game.time+=4;game.updateBoxes();assert.equal(game.boxes.get(boxEntity.target).phase,'offered');game.use();assert.equal(awards.length,bought,'Taking an already paid box weapon is free');assert.equal(sounds.at(-1),'lid_close');
const door=game.interactions.find(e=>e.targetname==='zombie_door');interact(door);assert.equal(awards.at(-1),-Number(door.zombie_cost));assert.equal(sounds.at(-1),'cha_ching');
game.pickup({type:'nuke',position:game.player.position.slice()});assert.equal(awards.at(-1),400);
for(let i=0;i<1000;i++)game.changePoints(10);assert.equal(game.scorePopups.length,64,'Burst awards must use bounded HUD storage');
game.time+=.51;game.expireScorePopups();assert.equal(game.scorePopups.length,0);game.changePoints(10);game.newGame();assert.equal(game.scorePopups.length,0);assert.equal(game.player.points,500);
const audio={};
for(const alias of ['cha_ching','no_cha_ching','repair_boards']){
  assert(manifest.sounds[alias]?.length,'Missing original '+alias);
  for(const s of manifest.sounds[alias]){const bytes=fs.readFileSync(new URL('../local-data/'+s.url.slice('/data/'.length),import.meta.url));assert.equal(bytes.toString('ascii',0,4),'RIFF');assert(bytes.length>1000);}
  audio[alias]=manifest.sounds[alias].map(s=>s.url);
}
const report={popup:{gains:'yellow +amount',costs:'dark red -amount',duration:.5,fadeStarts:.25,maxActive:64},transactions:{damage:true,headshot:true,doublePoints:true,wallWeapon:true,ammo:true,door:true,mysteryBox:true,rejection:true,repair:true,nuke:true},audio};
fs.writeFileSync(new URL('../local-data/score-feedback-verification.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
