export const MAPS=Object.freeze([
  {id:'nacht',title:'Nacht der Untoten',zone:'nacht',asset:'nazi_zombie_prototype',data:'gameplay',image:'loadscreen_zombie1',description:'You drove them deep into the heart of the Reich. You thought they were dead. You were wrong.'},
  {id:'verruckt',title:'Verrückt',zone:'verruckt',asset:'nazi_zombie_asylum',data:'gameplay/verruckt',image:'loadscreen_zombie_asylum',assetZones:['verruckt-patch','verruckt','common','nacht'],description:'Fight through a haunted asylum split in two. Restore power to reunite the halves, buy the first perks and use the electric traps.'},
  {id:'shi-no-numa',title:'Shi No Numa',zone:'shi-no-numa',asset:'nazi_zombie_sumpf',data:'gameplay/shi-no-numa',image:'loadscreen_zombie_sumpf',assetZones:['shi-no-numa-patch','shi-no-numa','common','nacht'],wawVision:{desaturation:.25,contrast:1.25,brightness:.09,darkTint:[.73,.74,.71],lightTint:[.8,.71,.7]},description:'The Swamp of Death. Survive the Japanese undead and Hellhounds, open the four huts, discover randomized perks, ride the zipline and put the Flogger to work.'},
  {id:'der-riese',title:'Der Riese',zone:'der-riese',asset:'nazi_zombie_factory',data:'gameplay/der-riese',image:'loadscreen_zombie_factory',description:'The Giant is rising. Battle the undead at the secret research facility. Restore power and link the teleporters to unlock Pack-a-Punch.'}
]);
export const BO1_MAPS=Object.freeze([
  {id:'kino',game:'black-ops',title:'Kino der Toten',zone:'bo1-kino',asset:'zombie_theater',data:'gameplay/bo1-kino',image:'loadscreen_zombie_theater',assetZones:['bo1-kino','bo1-common','bo1-base','bo1-english','bo1-ui','bo1-frontend'],description:'Battle the undead in an abandoned theater. Restore power, link the teleporter and reach Pack-a-Punch in the projection room.'},
  {id:'five',game:'black-ops',engine:'five',modelLightScale:.1,modelLightMax:1,title:'Five',zone:'bo1-five',asset:'zombie_pentagon',data:'gameplay/bo1-five',image:'loadscreen_zombie_pentagon',characterNames:['John F. Kennedy','Robert McNamara','Richard Nixon','Fidel Castro'],characterArms:['viewmodel_usa_pow_arms','viewmodel_usa_pow_arms','viewmodel_usa_pow_arms','viewmodel_usa_pow_arms'],assetZones:['bo1-five-patch','bo1-five','bo1-common','bo1-base','bo1-five-english','bo1-english','bo1-ui','bo1-frontend'],vision:{saturation:[.5052,.5684,.3931],darkTint:[.7789,.9996,.9996],midTint:[.8843,1.0101,.9996],lightTint:[1.2206,1.2206,1.2315],contrast:[1.0104,1.0104,1.0104],midStart:.119313,midEnd:.319313,exposure:.5},description:'Defend the Pentagon offices, War Room and laboratories. Ride the elevators, raise DEFCON to 5, and stop the Pentagon Thief with Winter’s Howl.'},
  {id:'ascension',game:'black-ops',title:'Ascension',zone:'bo1-cosmodrome',asset:'zombie_cosmodrome',data:'gameplay/bo1-cosmodrome',image:'loadscreen_zombie_cosmodrome',assetZones:['bo1-cosmodrome-patch','bo1-cosmodrome','bo1-common','bo1-base','bo1-cosmodrome-english','bo1-english','bo1-ui','bo1-frontend'],description:'A Soviet cosmodrome overrun by the dead. Restore power, ride the lunar landers and reach Pack-a-Punch beneath the rocket.'},
  {id:'call-of-the-dead',game:'black-ops',engine:'call-of-the-dead',title:'Call of the Dead',zone:'bo1-coast',asset:'zombie_coast',data:'gameplay/bo1-coast',image:'loadscreen_zombie_coast',characterNames:['Sarah Michelle Gellar','Robert Englund','Danny Trejo','Michael Rooker'],characterArms:['viewmodel_zom_gellar_arms','viewmodel_zom_englund_arms','viewmodel_zom_trejo_arms','viewmodel_zom_rooker_arms'],assetZones:['bo1-coast-patch','bo1-coast','bo1-common','bo1-base','bo1-coast-english','bo1-english','bo1-ui','bo1-frontend'],vision:{saturation:[.7930,.6807,.5895],darkTint:[.7789,.9996,.9996],midTint:[.9261,.9893,.9996],lightTint:[.9996,.9996,.9053],contrast:[1,1,1],midStart:.1965,midEnd:.343875,exposure:.5},description:'A frozen film set, a wrecked ship and an undead director. Restore power, follow the lighthouse to Pack-a-Punch and keep George Romero calm.'},
  {id:'moon',game:'black-ops',engine:'moon',title:'Moon',zone:'bo1-moon',asset:'zombie_moon',data:'gameplay/bo1-moon',image:'loadscreen_zombie_moon',assetZones:['bo1-moon-patch','bo1-moon','bo1-common','bo1-base','bo1-moon-english','bo1-english','bo1-ui','bo1-frontend'],vision:{saturation:[.3298,.3298,.3298],darkTint:[.8421,.8843,.7789],midTint:[.8211,.8001,.7159],lightTint:[.9684,1.0523,.9473],contrast:[.9965,.9965,.9965],midStart:.192969,midEnd:.242094,exposure:.5},description:'Survive No Man’s Land, teleport to Griffin Station and equip the P.E.S. Explore the lunar tunnels and Biodome, confront the astronaut and wield the Wave Gun.'},
  {id:'shangri-la',game:'black-ops',engine:'shangri-la',title:'Shangri-La',zone:'bo1-temple',asset:'zombie_temple',data:'gameplay/bo1-temple',image:'loadscreen_zombie_temple',assetZones:['bo1-temple-patch','bo1-temple','bo1-common','bo1-base','bo1-temple-english','bo1-english','bo1-ui','bo1-frontend'],vision:{saturation:[.9122,.7859,1.0737],darkTint:[1.0095,1.0941,1.5996],midTint:[1.0523,.9893,1.0942],lightTint:[1.3682,1.7263,1.8103],contrast:[1.0388,1.0456,1.0246],midStart:.185969,midEnd:.308750,exposure:.5},description:'A lost jungle temple. Restore both water wheels, find randomized perks, unlock Pack-a-Punch with the pressure plates and face Napalm Zombies and Shriekers with the 31-79 JGb215.'},
  {id:'dead-ops',game:'black-ops',engine:'dead-ops',title:'Dead Ops Arcade',zone:'bo1-doa',asset:'zombietron',data:'gameplay/bo1-doa',image:'loadscreen_zombietron',assetZones:['bo1-doa-patch','bo1-doa','bo1-doa-english','bo1-doa-common','bo1-common','bo1-base','bo1-ui'],description:'The original overhead arcade arenas. Fight waves of zombies, collect treasure and weapons, use speed boosts and nukes, and confront the Cosmic Silverback.'}
]);
export const BO2_MAPS=Object.freeze([
  {id:'buried',game:'black-ops-2',title:'Buried',zone:'bo2-buried',asset:'zm_buried',data:'gameplay/bo2-buried',image:'loadscreen_buried_zclassic_processing',assetZones:['bo2-patch','bo2-classic','bo2-buried','bo2-base','bo2-common','bo2-english','bo2-dlc','bo2-menu','bo2-ui-base','bo2-ui'],description:'An old mining town lies buried beneath the surface. Descend into the darkness, restore power and survive the undead.'},
  {id:'tranzit',game:'black-ops-2',title:'TranZit',zone:'bo2-tranzit',asset:'zm_transit',data:'gameplay/bo2-tranzit',image:'tranzit-load',assetZones:['bo2-tranzit-patch','bo2-tranzit-classic','bo2-tranzit','bo2-tranzit-english',...['busstation','diner','farm','powerstation','town','cornfield','forest','forest2','tunnel','labs','bridge'].map(p=>'bo2-tranzit-'+p),'bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Ride the bus through Green Run. Scavenge parts, build the Turbine, restore power and survive the fog and lava between the Bus Depot, Diner, Farm, Power Station and Town.'},
  {id:'town',game:'black-ops-2',modelLightScale:.65,modelLightMax:1.15,title:'Town',zone:'bo2-town',asset:'zm_transit_town',menuPlace:'zm_transit',data:'gameplay/bo2-town',image:'town-load',characterNames:['CIA Agent','CDC Soldier','CIA Agent','CDC Soldier'],characterArms:['c_zom_suit_viewhands','c_zom_hazmat_viewhands','c_zom_suit_viewhands','c_zom_hazmat_viewhands'],assetZones:['bo2-town','bo2-town-mode','bo2-town-english','bo2-tranzit-patch','bo2-tranzit-classic','bo2-tranzit','bo2-tranzit-english',...['town','busstation','diner','farm','powerstation','cornfield','forest','forest2','tunnel','labs','bridge'].map(p=>'bo2-tranzit-'+p),'bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Green Run · Survival. Hold out in the ruined Town, jump the lava, buy perks and wall weapons, and Pack-a-Punch in the street. Power is already on.'},
  {id:'nuketown',game:'black-ops-2',title:'Nuketown Zombies',zone:'bo2-nuketown',asset:'zm_nuked',data:'gameplay/bo2-nuketown',image:'nuketown-load',characterNames:['CIA Agent','CDC Soldier','CIA Agent','CDC Soldier'],characterArms:['c_zom_suit_viewhands','c_zom_hazmat_viewhands_light','c_zom_suit_viewhands','c_zom_hazmat_viewhands_light'],assetZones:['bo2-nuketown-patch','bo2-nuketown','bo2-nuketown-english','bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Battle the undead in the ruins of Nuketown. Perks and Pack-a-Punch fall from the sky as the rounds advance.'},
  {id:'die-rise',game:'black-ops-2',title:'Die Rise',zone:'bo2-die-rise',asset:'zm_highrise',data:'gameplay/bo2-die-rise',image:'die-rise-load',assetZones:['bo2-die-rise-patch','bo2-die-rise','bo2-die-rise-english','bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Fight through a collapsing Shanghai skyscraper. Ride the elevators to their perk machines, drop down in the escape pod, build the Trample Steam and Sliquifier, and survive the leapers.'},
  {id:'origins',game:'black-ops-2',characterNames:['Dempsey','Nikolai','Takeo','Richtofen'],characterArms:['c_zom_dempsey_viewhands','c_zom_nikolai_viewhands','c_zom_takeo_viewhands','c_zom_richtofen_viewhands'],title:'Origins',zone:'bo2-origins',asset:'zm_tomb',data:'gameplay/bo2-origins',image:'origins-load',assetZones:['bo2-origins-patch','bo2-origins','bo2-origins-english','bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Return to the trenches of northern France. Defend six generators, excavate the battlefield and face the Panzer Soldat. Origins browser port — in development.'},
  {id:'mob-of-the-dead',game:'black-ops-2',title:'Mob of the Dead',zone:'bo2-mob',asset:'zm_prison',data:'gameplay/bo2-mob',image:'mob-load',characterNames:['Finn O’Leary','Sal DeLuca','Billy Handsome','Albert Arlington'],characterArms:['c_zom_oleary_shortsleeve_viewhands','c_zom_deluca_longsleeve_viewhands','c_zom_handsome_sleeveless_viewhands','c_zom_arlington_coat_viewhands'],assetZones:['bo2-mob-patch','bo2-mob-classic','bo2-mob','bo2-mob-english','bo2-base','bo2-common','bo2-english','bo2-menu','bo2-ui-base','bo2-ui'],description:'Escape Alcatraz. Enter Afterlife to power the prison, face Brutus, assemble Icarus and reach Pack-a-Punch on the Golden Gate Bridge.'}
]);
export const ALL_MAPS=Object.freeze([...MAPS,...BO1_MAPS,...BO2_MAPS]);
export function mapById(id){return ALL_MAPS.find(map=>map.id===id)||MAPS[0];}
export function selectedMap(){
  if(typeof location!=='undefined'){
    if(location.pathname.startsWith('/black-ops-2'))return BO2_MAPS.find(m=>m.id===new URLSearchParams(location.search).get('map'))||BO2_MAPS[0];
    if(location.pathname.startsWith('/black-ops'))return BO1_MAPS.find(m=>m.id===new URLSearchParams(location.search).get('map'))||BO1_MAPS[0];
  }
  return MAPS.find(m=>m.id===(typeof location==='undefined'?'nacht':new URLSearchParams(location.search).get('map')))||MAPS[0];
}
